/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica_basica;

/**
 *
 * @author alexfduron
 */
public class Grafica_View extends javax.swing.JFrame {

    /**
     * Creates new form Grafica_View
     */
    public Grafica_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Dibujar = new javax.swing.JButton();
        Pnl_Lienzo = new javax.swing.JPanel();
        Lbl_X = new javax.swing.JLabel();
        Lbl_Y = new javax.swing.JLabel();
        Lbl_X2 = new javax.swing.JLabel();
        Lbl_Y2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_Dibujar.setText("Dibujar Tren");
        Btn_Dibujar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DibujarMouseClicked(evt);
            }
        });

        Pnl_Lienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pnl_Lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Pnl_LienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout Pnl_LienzoLayout = new javax.swing.GroupLayout(Pnl_Lienzo);
        Pnl_Lienzo.setLayout(Pnl_LienzoLayout);
        Pnl_LienzoLayout.setHorizontalGroup(
            Pnl_LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        Pnl_LienzoLayout.setVerticalGroup(
            Pnl_LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        Lbl_X.setText("Valor X:");

        Lbl_Y.setText("Valor Y:");

        Lbl_X2.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_X2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lbl_X2.setText("0");
        Lbl_X2.setToolTipText("");
        Lbl_X2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lbl_Y2.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_Y2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lbl_Y2.setText("0");
        Lbl_Y2.setToolTipText("");
        Lbl_Y2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Dibujar)
                        .addGap(51, 51, 51)
                        .addComponent(Lbl_X)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_X2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Lbl_Y)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lbl_Y2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Dibujar)
                    .addComponent(Lbl_X)
                    .addComponent(Lbl_Y)
                    .addComponent(Lbl_X2)
                    .addComponent(Lbl_Y2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pnl_Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DibujarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DibujarMouseClicked
        
        // Dibujar una linea
        //Dibujo.HacerLinea(Pnl_Lienzo.getGraphics(), 0, 0, 50, 50, "Rojo");
        
        //Dibujar un cuadro
        //Dibujo.HacerCuadro(Pnl_Lienzo.getGraphics(), 50, 50, 100, 50, "Amarillo");
        
        //Dibujar un Circulo
        //Dibujo.HacerCirculo(Pnl_Lienzo.getGraphics(), 50, 50, 100, "Verde");
        
        //Dibujar un cuadroredondeado
        //Dibujo.HacerCuadroRedondeado(Pnl_Lienzo.getGraphics(), 50, 50, 100, 50, 25, 25, "Azul");
        
        //locomotora
            //motor
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 70, 100, 80, 80, "Naranja");
            //cabina
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 150, 60, 60, 120, "Naranja");
            //ventana
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 160, 70, 40, 40, "");
            //techo
            Dibujo.HacerCuadroRedondeadoRelleno(this.Pnl_Lienzo.getGraphics(), 140, 50, 80, 10, 10, 10, "Rojo");
            //chimenea 1
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 80, 60, 15, 40, "Rojo");
            //chimenea 2
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 75, 50, 25, 10, "Naranja");
            //gancho vagon
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 210, 135, 35, 10, "Naranja");
            //llanta locomotora
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 80, 190, 20, "Rosado");
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 140, 190, 20, "Rosado");
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 180, 180, 40, "Rosado");
            //Parachoques
            Dibujo.HacerArcoRelleno(this.Pnl_Lienzo.getGraphics(), 40, 140, 60, 120, 90, 90, "Rojo");
            
        //vagon 1
            //caja
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 240, 100, 80, 80, "Rojo");
            //figura
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 260, 120, 40, 40, "Amarillo");
            //techo
            Dibujo.HacerCuadroRedondeadoRelleno(this.Pnl_Lienzo.getGraphics(), 230, 90, 100, 10, 10, 10, "Naranja");
            //gancho vagon
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 320, 135, 35, 10, "Naranja");
            //llanta vagon1
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 250, 190, 20, "Rosado");
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 310, 190, 20, "Rosado");
            
        //vagon 2
            //caja
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 350, 100, 80, 80, "Rojo");
            //techo
            Dibujo.HacerCuadroRedondeadoRelleno(this.Pnl_Lienzo.getGraphics(), 340, 90, 100, 10, 10, 10, "Naranja");
            //gancho vagon
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 430, 135, 35, 10, "Naranja");
            //llanta vagon 2
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 360, 190, 20, "Rosado");
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 420, 190, 20, "Rosado");
            //tirangulo
            int X1 = 370;
            int Y1 = 120;
            
            int[] valoresX = {0 + X1, 40 + X1, 20 + X1};
            int[] valoresY = {40 + Y1, 40 + Y1, 0 + Y1};
            int Lado = 3;
            
            Dibujo.HacerPoligonoRelleno(this.Pnl_Lienzo.getGraphics(), valoresX, valoresY, Lado, "Azul");
            
        //vagon3
            //caja
            Dibujo.HacerCuadroRelleno(this.Pnl_Lienzo.getGraphics(), 460, 100, 80, 80, "Rojo");
            //techo
            Dibujo.HacerCuadroRedondeadoRelleno(this.Pnl_Lienzo.getGraphics(), 450, 90, 100, 10, 10, 10, "Naranja");
            //llanta vagon 3
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 470, 190, 20, "Rosado");
            Dibujo.HacerCirculoRelleno(this.Pnl_Lienzo.getGraphics(), 530, 190, 20, "Rosado");
            //hexagono
            int X2 = 480;
            int Y2 = 120;
            
            int[] valoresX2 = {0 + X2, 10 + X2, 30 + X2, 40 + X2, 30 + X2, 10 + X2};
            int[] valoresY2 = {20 + Y2, 40 + Y2, 40 + Y2, 20 + Y2, 0 + Y2, 0 + Y2};
            int Lado2 = 6;
            
            Dibujo.HacerPoligonoRelleno(this.Pnl_Lienzo.getGraphics(), valoresX2, valoresY2, Lado2, "Verde");
        
        
    }//GEN-LAST:event_Btn_DibujarMouseClicked

    private void Pnl_LienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pnl_LienzoMouseMoved
        
        int X1 = evt.getX();
        
        int Y1 = evt.getY();
        
        this.Lbl_X2.setText(String.valueOf(X1));
        
        this.Lbl_Y2.setText(String.valueOf(Y1));
        
    }//GEN-LAST:event_Pnl_LienzoMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Dibujar;
    private javax.swing.JLabel Lbl_X;
    private javax.swing.JLabel Lbl_X2;
    private javax.swing.JLabel Lbl_Y;
    private javax.swing.JLabel Lbl_Y2;
    private javax.swing.JPanel Pnl_Lienzo;
    // End of variables declaration//GEN-END:variables
}
